jdbc.dbType=MYSQL
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://dev-db-host:3306/toydb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
jdbc.username=DEV_DB_USER
jdbc.password=DEV_DB_PASSWORD

APP_ENV=dev
IS_LOCAL=N

LOCAL_TEMP_ADMIN_PASSWORD=
LOCAL_TEMP_VERIFICATION_NUMBER=
VERIFICATION_EXPIRE_SECONDS=300

STORAGE=storage

SMS_HOST_URL=https://sens.apigw.ntruss.com
SMS_ACCESS_KEY=DEV_SMS_ACCESS_KEY
SMS_SECRET_KEY=DEV_SMS_SECRET_KEY
SMS_SERVICE_ID=DEV_SMS_SERVICE_ID
SMS_FROM_TEL=DEV_SMS_FROM_TEL
